apache:
        build: .
        volumes:
                - "./src:/var/www/html"
        links:
                - mysql
        ports:
                - "8080:80"

mysql:
        image: mysql:latest
        environment:
                - MYSQL_ROOT_PASSWORD=root
